apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-grocerylist4
  namespace: foobar-4
spec:
  replicas: 1
  selector:
    matchLabels:
      greymatter.io/cluster: edge_grocerylist4
  template:
    metadata:
      labels:
        greymatter.io/cluster: edge_grocerylist4
    spec:
      containers:
        - name: sidecar
          image: quay.io/greymatterio/gm-proxy:1.7.1
          imagePullPolicy: Always
          ports:
          - containerPort: 10812
            name: proxy
          env:
            - name: XDS_CLUSTER
              value: edge_grocerylist4
            - name: ENVOY_ADMIN_LOG_PATH
              value: /dev/stdout
            - name: PROXY_DYNAMIC
              value: "true"
            - name: XDS_ZONE
              value: default-zone
            - name: XDS_HOST
              value: controlensemble.greymatter.svc.cluster.local
            - name: XDS_PORT
              value: "50000"
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
      - name: gm-docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: edge-grocerylist4
  namespace: foobar-4
spec:
  ports:
  - name: ingress
    port: 10812
    protocol: TCP
    targetPort: 10812
  selector:
    greymatter.io/cluster: edge_grocerylist4
  type: LoadBalancer

